[package]
name = "enforcement_pack"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
dylint_linting = "5.0"

[dev-dependencies]

[package.metadata.rust-analyzer]
rustc_private = true
